import type { Creator, Meal } from "./types";

const creators: Record<string, Creator> = {
  noa: { id: "noa", name: "Noa Bell", handle: "@noasupper", location: "Lisbon", color: "#eb7d55" },
  iman: { id: "iman", name: "Iman Sari", handle: "@pantrynotes", location: "Bandung", color: "#668260" },
  june: { id: "june", name: "June Park", handle: "@junes.table", location: "Seoul", color: "#e0aa3e" },
  teo: { id: "teo", name: "Teo Martin", handle: "@weekdayteo", location: "Melbourne", color: "#5c6f91" },
  ama: { id: "ama", name: "Ama Owusu", handle: "@softpepper", location: "Accra", color: "#9a5c6b" },
  luca: { id: "luca", name: "Luca Rios", handle: "@gardenhour", location: "Valencia", color: "#6b8e4e" },
};

const post = (id: string, author: string, body: string, timeLabel: string) => ({ id, author, body, timeLabel });

export const meals: Meal[] = [
  {
    id: "miso-salmon-rice",
    name: "Miso lacquered salmon",
    summary: "Sticky miso salmon over ginger rice with a sharp cucumber tangle.",
    image: "",
    imageAlt: "Miso glazed salmon with rice and cucumber",
    accent: "#e36f4c",
    creator: creators.june!,
    tags: ["high-protein", "quick", "dairy-free"],
    cuisine: "Japanese-inspired",
    mealType: "dinner",
    prepMinutes: 28,
    servings: 2,
    calories: 612,
    protein: 42,
    carbs: 63,
    fat: 21,
    fiber: 5,
    micros: { iron: 16, calcium: 9, potassium: 24, vitaminC: 18, sodium: 31 },
    ingredients: [
      { name: "salmon fillet", quantity: 320, unit: "g", aisle: "protein" },
      { name: "white miso", quantity: 2, unit: "tbsp", aisle: "pantry" },
      { name: "short-grain rice", quantity: 1, unit: "cup", aisle: "pantry" },
      { name: "cucumber", quantity: 1, unit: "large", aisle: "produce" },
      { name: "fresh ginger", quantity: 2, unit: "cm", aisle: "produce" },
    ],
    instructions: ["Whisk miso with a splash of water and brush over the salmon.", "Roast at 220°C until glossy and just cooked.", "Fold ginger through the rice and serve with dressed cucumber."],
    discussion: [post("msr-1", "Mara", "The cucumber keeps the glaze from feeling too sweet. Excellent weeknight ratio.", "2 days ago"), post("msr-2", "Eli", "I doubled the ginger and would do it again.", "Yesterday")],
  },
  {
    id: "charred-chicken-peaches",
    name: "Charred chicken & peaches",
    summary: "Smoky chicken, ripe peaches and peppery leaves with a mustard pan dressing.",
    image: "",
    imageAlt: "Charred chicken and peaches with greens",
    accent: "#e7a337",
    creator: creators.noa!,
    tags: ["high-protein", "gluten-free", "quick"],
    cuisine: "Mediterranean",
    mealType: "dinner",
    prepMinutes: 25,
    servings: 2,
    calories: 488,
    protein: 46,
    carbs: 25,
    fat: 23,
    fiber: 6,
    micros: { iron: 14, calcium: 8, potassium: 27, vitaminC: 32, sodium: 19 },
    ingredients: [
      { name: "chicken breast", quantity: 360, unit: "g", aisle: "protein" },
      { name: "ripe peaches", quantity: 2, unit: "whole", aisle: "produce" },
      { name: "rocket", quantity: 100, unit: "g", aisle: "produce" },
      { name: "wholegrain mustard", quantity: 1, unit: "tbsp", aisle: "pantry" },
      { name: "walnuts", quantity: 30, unit: "g", aisle: "pantry" },
    ],
    instructions: ["Sear seasoned chicken until deeply browned and cooked through.", "Char peach wedges in the same pan.", "Whisk the pan juices with mustard and toss through the leaves."],
    discussion: [post("ccp-1", "Niko", "This is the rare salad that actually feels like dinner.", "3 days ago"), post("ccp-2", "Sana", "Nectarines worked perfectly when peaches were firm.", "Today")],
  },
  {
    id: "green-coconut-dal",
    name: "Green coconut dal",
    summary: "Silky lentils brightened with spinach, lime and a crackling cumin oil.",
    image: "",
    imageAlt: "Green coconut dal with lime and herbs",
    accent: "#64824e",
    creator: creators.iman!,
    tags: ["vegan", "gluten-free", "dairy-free"],
    cuisine: "South Asian-inspired",
    mealType: "dinner",
    prepMinutes: 38,
    servings: 4,
    calories: 436,
    protein: 19,
    carbs: 55,
    fat: 17,
    fiber: 16,
    micros: { iron: 42, calcium: 18, potassium: 31, vitaminC: 38, sodium: 16 },
    ingredients: [
      { name: "red lentils", quantity: 1.5, unit: "cups", aisle: "pantry" },
      { name: "coconut milk", quantity: 400, unit: "ml", aisle: "pantry" },
      { name: "spinach", quantity: 180, unit: "g", aisle: "produce" },
      { name: "lime", quantity: 2, unit: "whole", aisle: "produce" },
      { name: "cumin seeds", quantity: 2, unit: "tsp", aisle: "spices" },
    ],
    instructions: ["Simmer lentils with coconut milk and water until tender.", "Blend spinach, coriander and lime into a loose green paste.", "Fold through the dal and finish with hot cumin oil."],
    discussion: [post("gcd-1", "Farah", "The lime at the end is non-negotiable—it wakes everything up.", "4 days ago"), post("gcd-2", "Jon", "Freezes well before adding the green paste.", "Yesterday")],
  },
  {
    id: "crispy-tofu-soba",
    name: "Crispy tofu soba",
    summary: "Buckwheat noodles, sesame greens and crisp-edged tofu in a citrus dressing.",
    image: "",
    imageAlt: "Crispy tofu and soba noodle bowl",
    accent: "#c85c55",
    creator: creators.june!,
    tags: ["vegan", "high-protein", "dairy-free"],
    cuisine: "Japanese-inspired",
    mealType: "lunch",
    prepMinutes: 24,
    servings: 2,
    calories: 522,
    protein: 27,
    carbs: 62,
    fat: 21,
    fiber: 9,
    micros: { iron: 28, calcium: 32, potassium: 18, vitaminC: 29, sodium: 24 },
    ingredients: [
      { name: "firm tofu", quantity: 300, unit: "g", aisle: "protein" },
      { name: "soba noodles", quantity: 180, unit: "g", aisle: "pantry" },
      { name: "pak choi", quantity: 2, unit: "heads", aisle: "produce" },
      { name: "sesame seeds", quantity: 1, unit: "tbsp", aisle: "pantry" },
      { name: "orange", quantity: 1, unit: "whole", aisle: "produce" },
    ],
    instructions: ["Press and sear tofu until all sides are crisp.", "Cook soba and blanch greens in the final minute.", "Toss with orange-sesame dressing and top with tofu."],
    discussion: [post("cts-1", "Mina", "Cold leftovers were even better for lunch.", "5 days ago"), post("cts-2", "Rae", "Use 100% buckwheat noodles if you need gluten-free.", "2 days ago")],
  },
  {
    id: "tomato-butter-beans",
    name: "Tomato butter beans",
    summary: "Creamy beans, blistered tomatoes and basil oil on thick sourdough.",
    image: "",
    imageAlt: "Tomato butter beans on toasted sourdough",
    accent: "#df6447",
    creator: creators.luca!,
    tags: ["vegetarian", "quick"],
    cuisine: "Spanish-inspired",
    mealType: "lunch",
    prepMinutes: 20,
    servings: 2,
    calories: 498,
    protein: 20,
    carbs: 68,
    fat: 17,
    fiber: 15,
    micros: { iron: 31, calcium: 19, potassium: 29, vitaminC: 45, sodium: 22 },
    ingredients: [
      { name: "butter beans", quantity: 480, unit: "g", aisle: "pantry" },
      { name: "cherry tomatoes", quantity: 300, unit: "g", aisle: "produce" },
      { name: "sourdough", quantity: 4, unit: "slices", aisle: "bakery" },
      { name: "basil", quantity: 1, unit: "bunch", aisle: "produce" },
      { name: "parmesan", quantity: 25, unit: "g", aisle: "dairy" },
    ],
    instructions: ["Blister tomatoes in olive oil until they slump.", "Add beans and simmer until creamy around the edges.", "Spoon over toast and streak with basil oil."],
    discussion: [post("tbb-1", "Owen", "Mashed a few beans into the sauce—instant silkiness.", "1 week ago"), post("tbb-2", "Priya", "Good with capers when parmesan is omitted.", "3 days ago")],
  },
  {
    id: "turmeric-chicken-bowl",
    name: "Turmeric chicken bowl",
    summary: "Golden chicken, herbed quinoa, pickled onion and a cool tahini spoon.",
    image: "",
    imageAlt: "Turmeric chicken grain bowl",
    accent: "#e3ad38",
    creator: creators.ama!,
    tags: ["high-protein", "gluten-free"],
    cuisine: "Middle Eastern-inspired",
    mealType: "lunch",
    prepMinutes: 32,
    servings: 2,
    calories: 571,
    protein: 45,
    carbs: 52,
    fat: 22,
    fiber: 10,
    micros: { iron: 24, calcium: 15, potassium: 27, vitaminC: 22, sodium: 20 },
    ingredients: [
      { name: "chicken thighs", quantity: 360, unit: "g", aisle: "protein" },
      { name: "quinoa", quantity: 1, unit: "cup", aisle: "pantry" },
      { name: "red onion", quantity: 1, unit: "whole", aisle: "produce" },
      { name: "tahini", quantity: 2, unit: "tbsp", aisle: "pantry" },
      { name: "turmeric", quantity: 2, unit: "tsp", aisle: "spices" },
    ],
    instructions: ["Coat chicken with turmeric, cumin and salt, then roast.", "Toss cooked quinoa with herbs and lemon.", "Layer with quick-pickled onion and tahini."],
    discussion: [post("tcb-1", "Nadia", "The pickled onion carries this through meal prep day three.", "6 days ago"), post("tcb-2", "Marc", "Used chickpeas in half the bowls and loved both.", "Yesterday")],
  },
  {
    id: "ricotta-pea-toast",
    name: "Ricotta pea toast",
    summary: "Lemony crushed peas and whipped ricotta on seedy toast with mint.",
    image: "",
    imageAlt: "Ricotta and green pea toast",
    accent: "#77a254",
    creator: creators.noa!,
    tags: ["vegetarian", "quick"],
    cuisine: "Modern European",
    mealType: "breakfast",
    prepMinutes: 14,
    servings: 2,
    calories: 382,
    protein: 19,
    carbs: 43,
    fat: 16,
    fiber: 9,
    micros: { iron: 16, calcium: 28, potassium: 18, vitaminC: 31, sodium: 17 },
    ingredients: [
      { name: "frozen peas", quantity: 220, unit: "g", aisle: "frozen" },
      { name: "ricotta", quantity: 160, unit: "g", aisle: "dairy" },
      { name: "seeded bread", quantity: 4, unit: "slices", aisle: "bakery" },
      { name: "mint", quantity: 1, unit: "small bunch", aisle: "produce" },
      { name: "lemon", quantity: 1, unit: "whole", aisle: "produce" },
    ],
    instructions: ["Blanch peas and crush with lemon and mint.", "Whip ricotta with a pinch of salt.", "Pile both onto hot toast and finish with pepper."],
    discussion: [post("rpt-1", "Cass", "A poached egg turns this into a serious brunch.", "2 days ago"), post("rpt-2", "Devi", "The pea mixture is also excellent as a dip.", "Today")],
  },
  {
    id: "oat-fig-breakfast",
    name: "Toasted oat & fig pot",
    summary: "Creamy overnight oats with roasted figs, pistachio and cardamom crunch.",
    image: "",
    imageAlt: "Overnight oats with roasted figs and pistachios",
    accent: "#a96572",
    creator: creators.teo!,
    tags: ["vegetarian", "quick"],
    cuisine: "Contemporary",
    mealType: "breakfast",
    prepMinutes: 10,
    servings: 2,
    calories: 426,
    protein: 16,
    carbs: 61,
    fat: 15,
    fiber: 11,
    micros: { iron: 22, calcium: 24, potassium: 19, vitaminC: 6, sodium: 7 },
    ingredients: [
      { name: "rolled oats", quantity: 1, unit: "cup", aisle: "pantry" },
      { name: "Greek yogurt", quantity: 220, unit: "g", aisle: "dairy" },
      { name: "fresh figs", quantity: 4, unit: "whole", aisle: "produce" },
      { name: "pistachios", quantity: 30, unit: "g", aisle: "pantry" },
      { name: "cardamom", quantity: 0.5, unit: "tsp", aisle: "spices" },
    ],
    instructions: ["Soak oats with yogurt and a little water overnight.", "Roast figs until jammy.", "Layer with pistachio and cardamom before serving."],
    discussion: [post("ofb-1", "Kira", "The roasted figs make this feel far more elaborate than ten minutes.", "1 week ago"), post("ofb-2", "Tom", "Pear works well outside fig season.", "4 days ago")],
  },
  {
    id: "sesame-egg-rice",
    name: "Sesame egg breakfast rice",
    summary: "Jammy eggs, sesame rice and wilted greens under a chili-crisp shine.",
    image: "",
    imageAlt: "Jammy eggs over sesame breakfast rice",
    accent: "#c84f3e",
    creator: creators.iman!,
    tags: ["vegetarian", "quick", "gluten-free"],
    cuisine: "East Asian-inspired",
    mealType: "breakfast",
    prepMinutes: 16,
    servings: 2,
    calories: 458,
    protein: 21,
    carbs: 55,
    fat: 18,
    fiber: 6,
    micros: { iron: 23, calcium: 17, potassium: 16, vitaminC: 26, sodium: 24 },
    ingredients: [
      { name: "eggs", quantity: 4, unit: "whole", aisle: "dairy" },
      { name: "cooked rice", quantity: 2, unit: "cups", aisle: "pantry" },
      { name: "spinach", quantity: 140, unit: "g", aisle: "produce" },
      { name: "sesame oil", quantity: 1, unit: "tbsp", aisle: "pantry" },
      { name: "chili crisp", quantity: 2, unit: "tsp", aisle: "pantry" },
    ],
    instructions: ["Boil eggs for seven minutes, chill and peel.", "Warm rice with sesame oil while wilting the spinach.", "Assemble with halved eggs and chili crisp."],
    discussion: [post("ser-1", "Lin", "Perfect use for last night's rice.", "3 days ago"), post("ser-2", "Ari", "Added edamame for more protein.", "Yesterday")],
  },
  {
    id: "harissa-cod-chickpeas",
    name: "Harissa cod & chickpeas",
    summary: "Flaky cod roasted over cumin chickpeas with lemony herbs.",
    image: "",
    imageAlt: "Harissa cod over chickpeas",
    accent: "#d45a42",
    creator: creators.luca!,
    tags: ["high-protein", "gluten-free", "dairy-free"],
    cuisine: "North African-inspired",
    mealType: "dinner",
    prepMinutes: 30,
    servings: 2,
    calories: 503,
    protein: 48,
    carbs: 48,
    fat: 15,
    fiber: 13,
    micros: { iron: 27, calcium: 11, potassium: 32, vitaminC: 34, sodium: 23 },
    ingredients: [
      { name: "cod fillets", quantity: 360, unit: "g", aisle: "protein" },
      { name: "chickpeas", quantity: 480, unit: "g", aisle: "pantry" },
      { name: "harissa", quantity: 1.5, unit: "tbsp", aisle: "pantry" },
      { name: "lemon", quantity: 1, unit: "whole", aisle: "produce" },
      { name: "coriander", quantity: 1, unit: "bunch", aisle: "produce" },
    ],
    instructions: ["Roast chickpeas with cumin until their edges crisp.", "Coat cod lightly with harissa and place over chickpeas.", "Roast until flaky and finish with lemon herbs."],
    discussion: [post("hcc-1", "Yara", "One tray, huge flavor, very little cleanup.", "5 days ago"), post("hcc-2", "Ben", "The chickpeas are worth making on their own.", "2 days ago")],
  },
  {
    id: "mushroom-polenta",
    name: "Mushroom pepper polenta",
    summary: "Soft parmesan polenta with glossy mushrooms, black pepper and herbs.",
    image: "",
    imageAlt: "Creamy polenta topped with mushrooms",
    accent: "#7b654f",
    creator: creators.teo!,
    tags: ["vegetarian", "gluten-free"],
    cuisine: "Northern Italian-inspired",
    mealType: "dinner",
    prepMinutes: 35,
    servings: 3,
    calories: 465,
    protein: 18,
    carbs: 54,
    fat: 21,
    fiber: 8,
    micros: { iron: 19, calcium: 26, potassium: 23, vitaminC: 9, sodium: 20 },
    ingredients: [
      { name: "mixed mushrooms", quantity: 450, unit: "g", aisle: "produce" },
      { name: "quick polenta", quantity: 1, unit: "cup", aisle: "pantry" },
      { name: "parmesan", quantity: 60, unit: "g", aisle: "dairy" },
      { name: "thyme", quantity: 1, unit: "small bunch", aisle: "produce" },
      { name: "black pepper", quantity: 2, unit: "tsp", aisle: "spices" },
    ],
    instructions: ["Brown mushrooms in batches until glossy and dark-edged.", "Whisk polenta into simmering water until soft.", "Fold in parmesan and crown with mushrooms and pepper."],
    discussion: [post("mpp-1", "Leah", "A proper cold-weather bowl without being heavy.", "6 days ago"), post("mpp-2", "Mo", "Added white beans beneath the mushrooms.", "2 days ago")],
  },
  {
    id: "ginger-turkey-cups",
    name: "Ginger turkey lettuce cups",
    summary: "Savory turkey, crunchy vegetables and herbs tucked into cool lettuce leaves.",
    image: "",
    imageAlt: "Ginger turkey in crisp lettuce cups",
    accent: "#73975e",
    creator: creators.ama!,
    tags: ["high-protein", "quick", "gluten-free", "dairy-free"],
    cuisine: "Southeast Asian-inspired",
    mealType: "lunch",
    prepMinutes: 22,
    servings: 2,
    calories: 397,
    protein: 39,
    carbs: 28,
    fat: 16,
    fiber: 7,
    micros: { iron: 20, calcium: 10, potassium: 25, vitaminC: 40, sodium: 26 },
    ingredients: [
      { name: "turkey mince", quantity: 350, unit: "g", aisle: "protein" },
      { name: "baby gem lettuce", quantity: 2, unit: "heads", aisle: "produce" },
      { name: "carrot", quantity: 2, unit: "whole", aisle: "produce" },
      { name: "fresh ginger", quantity: 3, unit: "cm", aisle: "produce" },
      { name: "lime", quantity: 1, unit: "whole", aisle: "produce" },
    ],
    instructions: ["Brown turkey hard with ginger and garlic.", "Add grated carrot and a savory lime dressing.", "Spoon into separated lettuce leaves and finish with herbs."],
    discussion: [post("gtc-1", "Bea", "Messy in exactly the right way.", "4 days ago"), post("gtc-2", "Sam", "Also great over rice when eating at a desk.", "Yesterday")],
  },
  {
    id: "roasted-cauliflower-tahini",
    name: "Roasted cauliflower tahini",
    summary: "Bronzed cauliflower, lemon tahini, lentils and a shower of herbs.",
    image: "",
    imageAlt: "Roasted cauliflower with tahini and lentils",
    accent: "#d39b44",
    creator: creators.noa!,
    tags: ["vegan", "gluten-free", "dairy-free"],
    cuisine: "Levantine-inspired",
    mealType: "lunch",
    prepMinutes: 34,
    servings: 3,
    calories: 441,
    protein: 18,
    carbs: 48,
    fat: 22,
    fiber: 16,
    micros: { iron: 29, calcium: 21, potassium: 31, vitaminC: 74, sodium: 14 },
    ingredients: [
      { name: "cauliflower", quantity: 1, unit: "large", aisle: "produce" },
      { name: "green lentils", quantity: 2, unit: "cups cooked", aisle: "pantry" },
      { name: "tahini", quantity: 3, unit: "tbsp", aisle: "pantry" },
      { name: "parsley", quantity: 1, unit: "bunch", aisle: "produce" },
      { name: "lemon", quantity: 2, unit: "whole", aisle: "produce" },
    ],
    instructions: ["Roast cauliflower at high heat until deeply bronzed.", "Loosen tahini with lemon and cold water.", "Layer lentils, cauliflower, sauce and herbs."],
    discussion: [post("rct-1", "Drew", "The leftovers make an excellent wrap filling.", "1 week ago"), post("rct-2", "Mimi", "Added pomegranate for a bright crunch.", "3 days ago")],
  },
  {
    id: "berry-kefir-bowl",
    name: "Berry kefir crunch",
    summary: "Tangy kefir, crushed berries, toasted seeds and oat clusters.",
    image: "",
    imageAlt: "Berry kefir breakfast bowl",
    accent: "#a84f71",
    creator: creators.luca!,
    tags: ["vegetarian", "quick", "gluten-free"],
    cuisine: "Contemporary",
    mealType: "breakfast",
    prepMinutes: 8,
    servings: 2,
    calories: 354,
    protein: 18,
    carbs: 44,
    fat: 13,
    fiber: 10,
    micros: { iron: 14, calcium: 31, potassium: 18, vitaminC: 39, sodium: 8 },
    ingredients: [
      { name: "plain kefir", quantity: 400, unit: "ml", aisle: "dairy" },
      { name: "mixed berries", quantity: 250, unit: "g", aisle: "produce" },
      { name: "pumpkin seeds", quantity: 30, unit: "g", aisle: "pantry" },
      { name: "gluten-free oats", quantity: 70, unit: "g", aisle: "pantry" },
      { name: "honey", quantity: 1, unit: "tbsp", aisle: "pantry" },
    ],
    instructions: ["Crush half the berries into the kefir.", "Toast oats and seeds in a dry pan.", "Layer everything and finish with honey."],
    discussion: [post("bkc-1", "Nell", "Tastes like summer and takes less time than toast.", "2 days ago"), post("bkc-2", "Pao", "Frozen berries work after a quick warm-up.", "Today")],
  },
  {
    id: "spiced-beef-herb-rice",
    name: "Spiced beef & herb rice",
    summary: "Crisp-edged beef, fragrant rice, herbs and cooling cucumber yogurt.",
    image: "",
    imageAlt: "Spiced beef with herb rice and cucumber yogurt",
    accent: "#b65b45",
    creator: creators.ama!,
    tags: ["high-protein", "gluten-free"],
    cuisine: "Persian-inspired",
    mealType: "dinner",
    prepMinutes: 36,
    servings: 3,
    calories: 637,
    protein: 43,
    carbs: 67,
    fat: 22,
    fiber: 7,
    micros: { iron: 35, calcium: 14, potassium: 25, vitaminC: 27, sodium: 21 },
    ingredients: [
      { name: "lean beef mince", quantity: 450, unit: "g", aisle: "protein" },
      { name: "basmati rice", quantity: 1.5, unit: "cups", aisle: "pantry" },
      { name: "cucumber", quantity: 1, unit: "large", aisle: "produce" },
      { name: "Greek yogurt", quantity: 180, unit: "g", aisle: "dairy" },
      { name: "mixed herbs", quantity: 2, unit: "bunches", aisle: "produce" },
    ],
    instructions: ["Fry beef with warm spices until crisp at the edges.", "Fold chopped herbs through steamed rice.", "Serve with salted cucumber yogurt."],
    discussion: [post("sbhr-1", "Iris", "The herb volume looked excessive until it hit the rice—trust it.", "5 days ago"), post("sbhr-2", "Zak", "A generous squeeze of lemon ties it together.", "Yesterday")],
  },
  {
    id: "lemongrass-prawn-noodles",
    name: "Lemongrass prawn noodles",
    summary: "Springy rice noodles, juicy prawns and crisp vegetables in a lime dressing.",
    image: "",
    imageAlt: "Lemongrass prawn rice noodles",
    accent: "#ef8a44",
    creator: creators.iman!,
    tags: ["high-protein", "quick", "gluten-free", "dairy-free"],
    cuisine: "Vietnamese-inspired",
    mealType: "lunch",
    prepMinutes: 23,
    servings: 2,
    calories: 471,
    protein: 34,
    carbs: 61,
    fat: 11,
    fiber: 7,
    micros: { iron: 17, calcium: 13, potassium: 20, vitaminC: 49, sodium: 27 },
    ingredients: [
      { name: "raw prawns", quantity: 300, unit: "g", aisle: "protein" },
      { name: "rice noodles", quantity: 180, unit: "g", aisle: "pantry" },
      { name: "lemongrass", quantity: 2, unit: "stalks", aisle: "produce" },
      { name: "carrot", quantity: 1, unit: "large", aisle: "produce" },
      { name: "lime", quantity: 2, unit: "whole", aisle: "produce" },
    ],
    instructions: ["Soak noodles until springy and drain well.", "Sear prawns with minced lemongrass.", "Toss with vegetables, herbs and a sharp lime dressing."],
    discussion: [post("lpn-1", "Tess", "Fast, bright, and not remotely sad desk lunch.", "4 days ago"), post("lpn-2", "An", "Double the dressing if packing ahead.", "2 days ago")],
  },
  {
    id: "pumpkin-white-bean-soup",
    name: "Pumpkin white bean soup",
    summary: "Velvety pumpkin and white beans with rosemary crumbs and chili oil.",
    image: "",
    imageAlt: "Pumpkin and white bean soup",
    accent: "#d97734",
    creator: creators.teo!,
    tags: ["vegan", "dairy-free"],
    cuisine: "Italian-inspired",
    mealType: "lunch",
    prepMinutes: 40,
    servings: 4,
    calories: 404,
    protein: 17,
    carbs: 61,
    fat: 12,
    fiber: 15,
    micros: { iron: 27, calcium: 15, potassium: 30, vitaminC: 33, sodium: 18 },
    ingredients: [
      { name: "pumpkin", quantity: 800, unit: "g", aisle: "produce" },
      { name: "cannellini beans", quantity: 480, unit: "g", aisle: "pantry" },
      { name: "vegetable stock", quantity: 800, unit: "ml", aisle: "pantry" },
      { name: "rosemary", quantity: 3, unit: "sprigs", aisle: "produce" },
      { name: "breadcrumbs", quantity: 0.75, unit: "cup", aisle: "bakery" },
    ],
    instructions: ["Roast pumpkin until caramelized at the edges.", "Blend most of the beans with pumpkin and stock.", "Top with whole beans, rosemary crumbs and chili oil."],
    discussion: [post("pwbs-1", "Greta", "The whole beans keep the texture interesting.", "1 week ago"), post("pwbs-2", "Lou", "Made a double batch and froze beautifully.", "3 days ago")],
  },
  {
    id: "banana-tahini-pancakes",
    name: "Banana tahini pancakes",
    summary: "Tender oat pancakes with sesame depth, banana and a bright berry spoon.",
    image: "",
    imageAlt: "Banana tahini pancakes with berries",
    accent: "#d6a148",
    creator: creators.june!,
    tags: ["vegetarian", "gluten-free"],
    cuisine: "Contemporary",
    mealType: "breakfast",
    prepMinutes: 22,
    servings: 2,
    calories: 492,
    protein: 19,
    carbs: 65,
    fat: 20,
    fiber: 11,
    micros: { iron: 22, calcium: 18, potassium: 24, vitaminC: 21, sodium: 12 },
    ingredients: [
      { name: "bananas", quantity: 2, unit: "whole", aisle: "produce" },
      { name: "oat flour", quantity: 1, unit: "cup", aisle: "pantry" },
      { name: "eggs", quantity: 2, unit: "whole", aisle: "dairy" },
      { name: "tahini", quantity: 2, unit: "tbsp", aisle: "pantry" },
      { name: "berries", quantity: 150, unit: "g", aisle: "produce" },
    ],
    instructions: ["Mash banana with eggs and tahini.", "Fold in oat flour and rest for five minutes.", "Cook small pancakes and serve with crushed berries."],
    discussion: [post("btp-1", "May", "Nutty without being too rich; kids demolished them.", "3 days ago"), post("btp-2", "Sol", "Letting the batter rest really improves the flip.", "Today")],
  },
];

export const mealById = new Map(meals.map((meal) => [meal.id, meal]));

export const creatorCount = new Set(meals.map((meal) => meal.creator.id)).size;
