import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { createUserLayer, resolveConfiguration } from "../composition/layer";
import { applyOperations } from "../composition/operations";
import { SIDE_BY_SIDE_EXPORT_PATH, sideBySideOperations } from "../test/sideBySideConfiguration";
import { deriveTools } from "../webmcp/derived";
import { resetDatabaseForTests } from "./db";
import { validateImportBundle, type YourWebBundle } from "./export";
import { YourWebStore } from "./store";

/**
 * The shipped-adjacent demo bundle is generated by the kernel itself rather than hand-written, so
 * it cannot drift from the grammar. Run `npm run export:demo` to rewrite it after a change.
 */
const buildBundle = (): YourWebBundle => {
  const applied = applyOperations(createUserLayer(), sideBySideOperations);
  if (!applied.ok) throw new Error(`${applied.code}: ${applied.message}`);
  return {
    format: "yourweb-bundle",
    formatVersion: 2,
    capabilityVersion: 2,
    exportedAt: "2026-09-03T00:00:00.000Z",
    layer: { ...applied.layer, revision: 1 },
  };
};

const filePath = resolve(process.cwd(), SIDE_BY_SIDE_EXPORT_PATH);
const serialise = (bundle: YourWebBundle) => `${JSON.stringify(bundle, null, 2)}\n`;

describe("the side-by-side demo bundle", () => {
  it("is a valid, importable bundle", () => {
    const bundle = buildBundle();
    const result = validateImportBundle(bundle);
    if (!result.ok) throw new Error(JSON.stringify(result.issues, null, 2));
    expect(result.ok).toBe(true);
    expect(bundle.customRecords).toBeUndefined();
  });

  it("collapses the built-in screens into one workspace plus a tracker", () => {
    const { configuration, index } = resolveConfiguration(buildBundle().layer);
    const visible = configuration.surfaces.filter((surface) => !surface.hidden);
    expect(visible.map((surface) => surface.id)).toEqual(["kitchen", "calories"]);
    expect(visible.every((surface) => surface.owner === "user")).toBe(true);

    // Hidden, never removed: the developer's screens are intact and can be restored.
    expect(index.get("discover")?.hidden).toBe(true);
    expect(index.get("week")?.hidden).toBe(true);
    expect(configuration.surfaces).toHaveLength(4);
  });

  it("puts the week grid and the catalogue in one split row", () => {
    const { configuration } = resolveConfiguration(buildBundle().layer);
    const kitchen = configuration.surfaces.find((surface) => surface.id === "kitchen")!;
    if (kitchen.root.kind !== "section") throw new Error("The kitchen root should be a section.");
    const split = kitchen.root.children.find((child) => child.id === "kitchen-split")!;
    if (split.kind !== "grid") throw new Error("kitchen-split should be a grid.");
    expect(split.columns).toBe("split");
    expect(split.children.map((child) => `${child.id}:${child.kind}`)).toEqual([
      "kitchen-calendar:calendar",
      "kitchen-market:collection",
    ]);
  });

  it("binds a drag on each screen, both within that screen", () => {
    const { configuration, index } = resolveConfiguration(buildBundle().layer);
    expect(configuration.interactions.map((interaction) => interaction.id)).toEqual(["plan-by-dragging", "log-by-dragging"]);
    for (const interaction of configuration.interactions) {
      expect(index.get(interaction.source.componentId)?.surfaceId).toBe(index.get(interaction.target.componentId)?.surfaceId);
    }
  });

  it("imports through the real store and derives the tracker's tools", async () => {
    await resetDatabaseForTests();
    const store = new YourWebStore();
    await store.initialize();
    const imported = await store.importBundle(JSON.parse(readFileSync(filePath, "utf8")));
    expect(imported.ok).toBe(true);

    const state = store.getSnapshot();
    expect(state.configuration.surfaces.filter((surface) => !surface.hidden).map((surface) => surface.id)).toEqual(["kitchen", "calories"]);
    expect(state.activeSurfaceId).toBe("kitchen");
    expect(deriveTools(store, state.configuration).map((tool) => tool.name)).toEqual([
      "list_intake_log",
      "add_intake_log",
      "remove_intake_log",
      "run_plan_by_dragging",
      "run_log_by_dragging",
    ]);
  });

  it("matches the committed file", () => {
    const bundle = buildBundle();
    if (import.meta.env.MODE === "update") {
      mkdirSync(dirname(filePath), { recursive: true });
      writeFileSync(filePath, serialise(bundle), "utf8");
    }
    expect(existsSync(filePath)).toBe(true);
    expect(JSON.parse(readFileSync(filePath, "utf8"))).toEqual(bundle);
  });
});
